# Generated by Django 4.2.16 on 2024-11-06 13:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='languages',
        ),
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language'),
            preserve_default=False,
        ),
    ]
