# Generated by Django 4.2.16 on 2024-11-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_languages_project_languages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='languages',
            new_name='language',
        ),
    ]
