# Generated by Django 4.2.16 on 2024-11-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_projects', '0001_initial'),
        ('projects', '0004_alter_project_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='projects', to='images_projects.imageproject'),
        ),
    ]
