# Generated by Django 4.2.16 on 2024-11-07 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_rename_abreviation_language_abbreviation'),
        ('projects', '0005_project_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'language')},
            },
        ),
    ]
