# Generated by Django 4.2.16 on 2024-11-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_category_area_id'),
        ('projects', '0006_projectdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(related_name='projects', to='categories.category'),
        ),
    ]
