# Generated by Django 4.2.16 on 2024-11-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_rename_abreviation_language_abbreviation'),
        ('projects', '0007_alter_project_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='language',
        ),
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='languages.language'),
        ),
    ]
