# Generated by Django 4.2.16 on 2024-11-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_rename_abreviation_language_abbreviation'),
        ('projects', '0008_remove_project_language_project_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.ManyToManyField(blank=True, related_name='projects', to='languages.language'),
        ),
    ]
