# Generated by Django 4.2.16 on 2024-11-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(upload_to='images/companies/'),
        ),
    ]
