# Generated by Django 4.2.16 on 2024-11-06 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color_text', models.CharField(max_length=7)),
                ('color_bg', models.CharField(max_length=7)),
                ('logo', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('imageBig', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.area')),
            ],
        ),
    ]
