# Generated by Django 4.2.16 on 2024-11-08 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('categories', '0004_categorydescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='area_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='areas.area'),
        ),
    ]
