# Generated by Django 4.2.16 on 2024-11-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_category_area_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
