# Generated by Django 4.2.16 on 2024-11-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_category_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='images/categories/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='imageBig',
            field=models.ImageField(upload_to='images/categories/'),
        ),
    ]
