# Generated by Django 4.2.16 on 2024-11-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_alter_category_image_alter_category_imagebig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
