# Generated by Django 4.2.16 on 2024-11-15 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_alter_category_logo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorydescription',
            unique_together=set(),
        ),
    ]
