# Generated by Django 4.2.16 on 2026-05-11 18:04

from django.db import migrations, models
import main.storage_backend


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_alter_categorydescription_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(storage=main.storage_backend.MediaStorage(), upload_to='images/categories/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='imageBig',
            field=models.ImageField(storage=main.storage_backend.MediaStorage(), upload_to='images/categories/'),
        ),
    ]
