# Generated by Django 4.2.16 on 2026-05-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_alter_contact_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="country",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="contact",
            name="country_code",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
