# Generated by Django 4.2.16 on 2024-11-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='abreviation',
            new_name='abbreviation',
        ),
    ]
