# Generated by Django 4.2.16 on 2024-11-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('stacks_description', models.TextField(blank=True, max_length=500)),
                ('about_me', models.TextField(blank=True, max_length=1000)),
                ('phone_1', models.CharField(blank=True, max_length=15)),
                ('phone_2', models.CharField(blank=True, max_length=15)),
                ('email_1', models.EmailField(max_length=255, unique=True)),
                ('email_2', models.EmailField(blank=True, max_length=255)),
            ],
        ),
    ]
