# Generated by Django 4.2.16 on 2026-05-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "information",
            "0002_alter_biography_about_me_alter_biography_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="biography",
            name="github",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="biography",
            name="linkedin",
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
