# Generated by Django 4.2.16 on 2024-11-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageproject',
            name='description',
        ),
        migrations.AddField(
            model_name='imageproject',
            name='name',
            field=models.CharField(default='default_image_name', max_length=100),
        ),
    ]
