# Generated by Django 4.2.16 on 2024-11-06 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('images_projects', '0002_remove_imageproject_description_imageproject_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageproject',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images Projects'},
        ),
        migrations.AddField(
            model_name='imageproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageproject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
