# Generated by Django 4.2.16 on 2024-11-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_projects', '0003_alter_imageproject_options_imageproject_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproject',
            name='image',
            field=models.ImageField(upload_to='images/projects/'),
        ),
    ]
