# Generated by Django 4.2.16 on 2026-05-11 18:04

from django.db import migrations, models
import main.storage_backend


class Migration(migrations.Migration):

    dependencies = [
        ('images_projects', '0004_alter_imageproject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproject',
            name='image',
            field=models.ImageField(storage=main.storage_backend.MediaStorage(), upload_to='images/projects/'),
        ),
    ]
